/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ChevronDirection, IconName } from "./utils/icons";
export { ChevronDirection, IconName } from "./utils/icons";
export namespace Components {
    interface SkBadge {
        /**
          * @default 'default'
         */
        "color": 'success' | 'warning' | 'error' | 'accent' | 'secondary' | 'default';
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default 'status'
         */
        "variant": 'status' | 'filled' | 'category' | 'ai-chip';
    }
    interface SkButton {
        "accessibleLabel"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "fullWidth": boolean;
        /**
          * @default false
         */
        "iconOnly": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'ghost' | 'destructive';
    }
    interface SkCaption {
        /**
          * @default 'left'
         */
        "align": 'left' | 'center';
    }
    interface SkHeading {
        /**
          * @default 'left'
         */
        "align": 'left' | 'center';
        /**
          * @default 'md'
         */
        "size": 'display' | 'lg' | 'md' | 'sm';
    }
    /**
     * sk-icon: Scalable SVG icon component
     * Icons inherit color from the text color (currentColor) and can be sized via the size prop.
     * @example <sk-icon name="arrow" size="24"></sk-icon>
     * <sk-icon name="chevron" dir="left"></sk-icon>
     */
    interface SkIcon {
        /**
          * Optional aria-label for accessibility
         */
        "accessibleLabel"?: string;
        /**
          * Direction for chevron icon (down, up, left, right) Only used when name is 'chevron'
          * @default 'down'
         */
        "direction": ChevronDirection;
        /**
          * The name of the icon to display
          * @default 'arrow'
         */
        "name": IconName;
        /**
          * The size of the icon in pixels
          * @default 16
         */
        "size": number;
    }
    interface SkSideDrawer {
        "header": string;
        "open": boolean;
    }
    interface SkText {
        /**
          * @default 'left'
         */
        "align": 'left' | 'center';
        /**
          * @default 'md'
         */
        "size": 'lg' | 'md' | 'sm';
    }
    interface SkToggle {
        "accessibleLabel"?: string;
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "label"?: string;
    }
}
export interface SkBadgeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSkBadgeElement;
}
export interface SkToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSkToggleElement;
}
declare global {
    interface HTMLSkBadgeElementEventMap {
        "skClick": MouseEvent;
    }
    interface HTMLSkBadgeElement extends Components.SkBadge, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSkBadgeElementEventMap>(type: K, listener: (this: HTMLSkBadgeElement, ev: SkBadgeCustomEvent<HTMLSkBadgeElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSkBadgeElementEventMap>(type: K, listener: (this: HTMLSkBadgeElement, ev: SkBadgeCustomEvent<HTMLSkBadgeElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSkBadgeElement: {
        prototype: HTMLSkBadgeElement;
        new (): HTMLSkBadgeElement;
    };
    interface HTMLSkButtonElement extends Components.SkButton, HTMLStencilElement {
    }
    var HTMLSkButtonElement: {
        prototype: HTMLSkButtonElement;
        new (): HTMLSkButtonElement;
    };
    interface HTMLSkCaptionElement extends Components.SkCaption, HTMLStencilElement {
    }
    var HTMLSkCaptionElement: {
        prototype: HTMLSkCaptionElement;
        new (): HTMLSkCaptionElement;
    };
    interface HTMLSkHeadingElement extends Components.SkHeading, HTMLStencilElement {
    }
    var HTMLSkHeadingElement: {
        prototype: HTMLSkHeadingElement;
        new (): HTMLSkHeadingElement;
    };
    /**
     * sk-icon: Scalable SVG icon component
     * Icons inherit color from the text color (currentColor) and can be sized via the size prop.
     * @example <sk-icon name="arrow" size="24"></sk-icon>
     * <sk-icon name="chevron" dir="left"></sk-icon>
     */
    interface HTMLSkIconElement extends Components.SkIcon, HTMLStencilElement {
    }
    var HTMLSkIconElement: {
        prototype: HTMLSkIconElement;
        new (): HTMLSkIconElement;
    };
    interface HTMLSkSideDrawerElement extends Components.SkSideDrawer, HTMLStencilElement {
    }
    var HTMLSkSideDrawerElement: {
        prototype: HTMLSkSideDrawerElement;
        new (): HTMLSkSideDrawerElement;
    };
    interface HTMLSkTextElement extends Components.SkText, HTMLStencilElement {
    }
    var HTMLSkTextElement: {
        prototype: HTMLSkTextElement;
        new (): HTMLSkTextElement;
    };
    interface HTMLSkToggleElementEventMap {
        "skChange": boolean;
    }
    interface HTMLSkToggleElement extends Components.SkToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSkToggleElementEventMap>(type: K, listener: (this: HTMLSkToggleElement, ev: SkToggleCustomEvent<HTMLSkToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSkToggleElementEventMap>(type: K, listener: (this: HTMLSkToggleElement, ev: SkToggleCustomEvent<HTMLSkToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSkToggleElement: {
        prototype: HTMLSkToggleElement;
        new (): HTMLSkToggleElement;
    };
    interface HTMLElementTagNameMap {
        "sk-badge": HTMLSkBadgeElement;
        "sk-button": HTMLSkButtonElement;
        "sk-caption": HTMLSkCaptionElement;
        "sk-heading": HTMLSkHeadingElement;
        "sk-icon": HTMLSkIconElement;
        "sk-side-drawer": HTMLSkSideDrawerElement;
        "sk-text": HTMLSkTextElement;
        "sk-toggle": HTMLSkToggleElement;
    }
}
declare namespace LocalJSX {
    interface SkBadge {
        /**
          * @default 'default'
         */
        "color"?: 'success' | 'warning' | 'error' | 'accent' | 'secondary' | 'default';
        /**
          * @default ''
         */
        "label"?: string;
        "onSkClick"?: (event: SkBadgeCustomEvent<MouseEvent>) => void;
        /**
          * @default 'status'
         */
        "variant"?: 'status' | 'filled' | 'category' | 'ai-chip';
    }
    interface SkButton {
        "accessibleLabel"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * @default false
         */
        "iconOnly"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'ghost' | 'destructive';
    }
    interface SkCaption {
        /**
          * @default 'left'
         */
        "align"?: 'left' | 'center';
    }
    interface SkHeading {
        /**
          * @default 'left'
         */
        "align"?: 'left' | 'center';
        /**
          * @default 'md'
         */
        "size"?: 'display' | 'lg' | 'md' | 'sm';
    }
    /**
     * sk-icon: Scalable SVG icon component
     * Icons inherit color from the text color (currentColor) and can be sized via the size prop.
     * @example <sk-icon name="arrow" size="24"></sk-icon>
     * <sk-icon name="chevron" dir="left"></sk-icon>
     */
    interface SkIcon {
        /**
          * Optional aria-label for accessibility
         */
        "accessibleLabel"?: string;
        /**
          * Direction for chevron icon (down, up, left, right) Only used when name is 'chevron'
          * @default 'down'
         */
        "direction"?: ChevronDirection;
        /**
          * The name of the icon to display
          * @default 'arrow'
         */
        "name"?: IconName;
        /**
          * The size of the icon in pixels
          * @default 16
         */
        "size"?: number;
    }
    interface SkSideDrawer {
        "header"?: string;
        "open"?: boolean;
    }
    interface SkText {
        /**
          * @default 'left'
         */
        "align"?: 'left' | 'center';
        /**
          * @default 'md'
         */
        "size"?: 'lg' | 'md' | 'sm';
    }
    interface SkToggle {
        "accessibleLabel"?: string;
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "label"?: string;
        "onSkChange"?: (event: SkToggleCustomEvent<boolean>) => void;
    }

    interface SkBadgeAttributes {
        "variant": 'status' | 'filled' | 'category' | 'ai-chip';
        "color": 'success' | 'warning' | 'error' | 'accent' | 'secondary' | 'default';
        "label": string;
    }
    interface SkButtonAttributes {
        "variant": 'primary' | 'secondary' | 'ghost' | 'destructive';
        "size": 'sm' | 'md' | 'lg';
        "disabled": boolean;
        "loading": boolean;
        "fullWidth": boolean;
        "iconOnly": boolean;
        "type": 'button' | 'submit' | 'reset';
        "accessibleLabel": string;
    }
    interface SkCaptionAttributes {
        "align": 'left' | 'center';
    }
    interface SkHeadingAttributes {
        "size": 'display' | 'lg' | 'md' | 'sm';
        "align": 'left' | 'center';
    }
    interface SkIconAttributes {
        "name": IconName;
        "size": number;
        "direction": ChevronDirection;
        "accessibleLabel": string;
    }
    interface SkSideDrawerAttributes {
        "header": string;
        "open": boolean;
    }
    interface SkTextAttributes {
        "size": 'lg' | 'md' | 'sm';
        "align": 'left' | 'center';
    }
    interface SkToggleAttributes {
        "checked": boolean;
        "disabled": boolean;
        "label": string;
        "accessibleLabel": string;
    }

    interface IntrinsicElements {
        "sk-badge": Omit<SkBadge, keyof SkBadgeAttributes> & { [K in keyof SkBadge & keyof SkBadgeAttributes]?: SkBadge[K] } & { [K in keyof SkBadge & keyof SkBadgeAttributes as `attr:${K}`]?: SkBadgeAttributes[K] } & { [K in keyof SkBadge & keyof SkBadgeAttributes as `prop:${K}`]?: SkBadge[K] };
        "sk-button": Omit<SkButton, keyof SkButtonAttributes> & { [K in keyof SkButton & keyof SkButtonAttributes]?: SkButton[K] } & { [K in keyof SkButton & keyof SkButtonAttributes as `attr:${K}`]?: SkButtonAttributes[K] } & { [K in keyof SkButton & keyof SkButtonAttributes as `prop:${K}`]?: SkButton[K] };
        "sk-caption": Omit<SkCaption, keyof SkCaptionAttributes> & { [K in keyof SkCaption & keyof SkCaptionAttributes]?: SkCaption[K] } & { [K in keyof SkCaption & keyof SkCaptionAttributes as `attr:${K}`]?: SkCaptionAttributes[K] } & { [K in keyof SkCaption & keyof SkCaptionAttributes as `prop:${K}`]?: SkCaption[K] };
        "sk-heading": Omit<SkHeading, keyof SkHeadingAttributes> & { [K in keyof SkHeading & keyof SkHeadingAttributes]?: SkHeading[K] } & { [K in keyof SkHeading & keyof SkHeadingAttributes as `attr:${K}`]?: SkHeadingAttributes[K] } & { [K in keyof SkHeading & keyof SkHeadingAttributes as `prop:${K}`]?: SkHeading[K] };
        "sk-icon": Omit<SkIcon, keyof SkIconAttributes> & { [K in keyof SkIcon & keyof SkIconAttributes]?: SkIcon[K] } & { [K in keyof SkIcon & keyof SkIconAttributes as `attr:${K}`]?: SkIconAttributes[K] } & { [K in keyof SkIcon & keyof SkIconAttributes as `prop:${K}`]?: SkIcon[K] };
        "sk-side-drawer": Omit<SkSideDrawer, keyof SkSideDrawerAttributes> & { [K in keyof SkSideDrawer & keyof SkSideDrawerAttributes]?: SkSideDrawer[K] } & { [K in keyof SkSideDrawer & keyof SkSideDrawerAttributes as `attr:${K}`]?: SkSideDrawerAttributes[K] } & { [K in keyof SkSideDrawer & keyof SkSideDrawerAttributes as `prop:${K}`]?: SkSideDrawer[K] };
        "sk-text": Omit<SkText, keyof SkTextAttributes> & { [K in keyof SkText & keyof SkTextAttributes]?: SkText[K] } & { [K in keyof SkText & keyof SkTextAttributes as `attr:${K}`]?: SkTextAttributes[K] } & { [K in keyof SkText & keyof SkTextAttributes as `prop:${K}`]?: SkText[K] };
        "sk-toggle": Omit<SkToggle, keyof SkToggleAttributes> & { [K in keyof SkToggle & keyof SkToggleAttributes]?: SkToggle[K] } & { [K in keyof SkToggle & keyof SkToggleAttributes as `attr:${K}`]?: SkToggleAttributes[K] } & { [K in keyof SkToggle & keyof SkToggleAttributes as `prop:${K}`]?: SkToggle[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sk-badge": LocalJSX.IntrinsicElements["sk-badge"] & JSXBase.HTMLAttributes<HTMLSkBadgeElement>;
            "sk-button": LocalJSX.IntrinsicElements["sk-button"] & JSXBase.HTMLAttributes<HTMLSkButtonElement>;
            "sk-caption": LocalJSX.IntrinsicElements["sk-caption"] & JSXBase.HTMLAttributes<HTMLSkCaptionElement>;
            "sk-heading": LocalJSX.IntrinsicElements["sk-heading"] & JSXBase.HTMLAttributes<HTMLSkHeadingElement>;
            /**
             * sk-icon: Scalable SVG icon component
             * Icons inherit color from the text color (currentColor) and can be sized via the size prop.
             * @example <sk-icon name="arrow" size="24"></sk-icon>
             * <sk-icon name="chevron" dir="left"></sk-icon>
             */
            "sk-icon": LocalJSX.IntrinsicElements["sk-icon"] & JSXBase.HTMLAttributes<HTMLSkIconElement>;
            "sk-side-drawer": LocalJSX.IntrinsicElements["sk-side-drawer"] & JSXBase.HTMLAttributes<HTMLSkSideDrawerElement>;
            "sk-text": LocalJSX.IntrinsicElements["sk-text"] & JSXBase.HTMLAttributes<HTMLSkTextElement>;
            "sk-toggle": LocalJSX.IntrinsicElements["sk-toggle"] & JSXBase.HTMLAttributes<HTMLSkToggleElement>;
        }
    }
}
