/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Message } from "./components/ai-chat/ai-chat.types";
export { Message } from "./components/ai-chat/ai-chat.types";
export namespace Components {
    interface SkAiChat {
        /**
          * @default false
         */
        "auto": boolean;
        /**
          * @default true
         */
        "full": boolean;
        "header": string;
        "inputButtonLabel": string;
        "inputPlaceholder": string;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default "Assistant is typing"
         */
        "loadingLabel": string;
        /**
          * @default []
         */
        "messages": Message[];
        /**
          * @default true
         */
        "mockLoading": boolean;
        /**
          * @default 900
         */
        "mockLoadingDelay": number;
        /**
          * @default true
         */
        "mockStreaming": boolean;
        /**
          * @default ""
         */
        "streamingAssistantContent": string;
        "subheader": string;
        /**
          * @default [     "Create a summary from notes",     "Draft a release checklist",     "Explain this API surface",   ]
         */
        "suggestions": string[];
        "suggestionsLabel": string;
    }
    interface SkButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'Button'
         */
        "label": string;
        /**
          * @default 'm'
         */
        "size": 's' | 'm' | 'l';
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "ui": 'primary' | 'secondary' | 'tertiary' | 'ghost' | 'link';
    }
    interface SkInput {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "inputButtonDisabled": boolean;
        /**
          * @default "Send"
         */
        "inputButtonLabel": string;
        /**
          * @default "Ask anything..."
         */
        "inputPlaceholder": string;
    }
    interface SkLoading {
        /**
          * @default false
         */
        "active": boolean;
        /**
          * @default "Loading"
         */
        "label": string;
    }
    interface SkMessage {
        "avatarLabel"?: string;
        /**
          * @default ""
         */
        "content": string;
        /**
          * @default "assistant"
         */
        "messageRole": MessageRole;
        "timestamp"?: string;
    }
    interface SkSideDrawer {
        "header": string;
        "open": boolean;
    }
    interface SkSimpleStage {
        /**
          * @default 'Learn more'
         */
        "ctaLabel": string;
        /**
          * @default 'Simple stage description for a teaser section.'
         */
        "description": string;
        /**
          * @default 'Simple Stage Title'
         */
        "heading": string;
        /**
          * @default '78vh'
         */
        "maxHeight": string;
        /**
          * @default 'Stage teaser media'
         */
        "mediaAlt": string;
        "mediaSrc": string;
        /**
          * @default 'image'
         */
        "mediaType": 'image' | 'video';
        /**
          * @default '55vh'
         */
        "minHeight": string;
        "poster": string;
    }
    interface SkTypingIndicator {
    }
}
export interface SkAiChatCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSkAiChatElement;
}
export interface SkInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSkInputElement;
}
declare global {
    interface HTMLSkAiChatElementEventMap {
        "suggestionClick": string;
    }
    interface HTMLSkAiChatElement extends Components.SkAiChat, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSkAiChatElementEventMap>(type: K, listener: (this: HTMLSkAiChatElement, ev: SkAiChatCustomEvent<HTMLSkAiChatElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSkAiChatElementEventMap>(type: K, listener: (this: HTMLSkAiChatElement, ev: SkAiChatCustomEvent<HTMLSkAiChatElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSkAiChatElement: {
        prototype: HTMLSkAiChatElement;
        new (): HTMLSkAiChatElement;
    };
    interface HTMLSkButtonElement extends Components.SkButton, HTMLStencilElement {
    }
    var HTMLSkButtonElement: {
        prototype: HTMLSkButtonElement;
        new (): HTMLSkButtonElement;
    };
    interface HTMLSkInputElementEventMap {
        "messageSubmit": string;
    }
    interface HTMLSkInputElement extends Components.SkInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSkInputElementEventMap>(type: K, listener: (this: HTMLSkInputElement, ev: SkInputCustomEvent<HTMLSkInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSkInputElementEventMap>(type: K, listener: (this: HTMLSkInputElement, ev: SkInputCustomEvent<HTMLSkInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSkInputElement: {
        prototype: HTMLSkInputElement;
        new (): HTMLSkInputElement;
    };
    interface HTMLSkLoadingElement extends Components.SkLoading, HTMLStencilElement {
    }
    var HTMLSkLoadingElement: {
        prototype: HTMLSkLoadingElement;
        new (): HTMLSkLoadingElement;
    };
    interface HTMLSkMessageElement extends Components.SkMessage, HTMLStencilElement {
    }
    var HTMLSkMessageElement: {
        prototype: HTMLSkMessageElement;
        new (): HTMLSkMessageElement;
    };
    interface HTMLSkSideDrawerElement extends Components.SkSideDrawer, HTMLStencilElement {
    }
    var HTMLSkSideDrawerElement: {
        prototype: HTMLSkSideDrawerElement;
        new (): HTMLSkSideDrawerElement;
    };
    interface HTMLSkSimpleStageElement extends Components.SkSimpleStage, HTMLStencilElement {
    }
    var HTMLSkSimpleStageElement: {
        prototype: HTMLSkSimpleStageElement;
        new (): HTMLSkSimpleStageElement;
    };
    interface HTMLSkTypingIndicatorElement extends Components.SkTypingIndicator, HTMLStencilElement {
    }
    var HTMLSkTypingIndicatorElement: {
        prototype: HTMLSkTypingIndicatorElement;
        new (): HTMLSkTypingIndicatorElement;
    };
    interface HTMLElementTagNameMap {
        "sk-ai-chat": HTMLSkAiChatElement;
        "sk-button": HTMLSkButtonElement;
        "sk-input": HTMLSkInputElement;
        "sk-loading": HTMLSkLoadingElement;
        "sk-message": HTMLSkMessageElement;
        "sk-side-drawer": HTMLSkSideDrawerElement;
        "sk-simple-stage": HTMLSkSimpleStageElement;
        "sk-typing-indicator": HTMLSkTypingIndicatorElement;
    }
}
declare namespace LocalJSX {
    interface SkAiChat {
        /**
          * @default false
         */
        "auto"?: boolean;
        /**
          * @default true
         */
        "full"?: boolean;
        "header"?: string;
        "inputButtonLabel"?: string;
        "inputPlaceholder"?: string;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default "Assistant is typing"
         */
        "loadingLabel"?: string;
        /**
          * @default []
         */
        "messages"?: Message[];
        /**
          * @default true
         */
        "mockLoading"?: boolean;
        /**
          * @default 900
         */
        "mockLoadingDelay"?: number;
        /**
          * @default true
         */
        "mockStreaming"?: boolean;
        "onSuggestionClick"?: (event: SkAiChatCustomEvent<string>) => void;
        /**
          * @default ""
         */
        "streamingAssistantContent"?: string;
        "subheader"?: string;
        /**
          * @default [     "Create a summary from notes",     "Draft a release checklist",     "Explain this API surface",   ]
         */
        "suggestions"?: string[];
        "suggestionsLabel"?: string;
    }
    interface SkButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 'Button'
         */
        "label"?: string;
        /**
          * @default 'm'
         */
        "size"?: 's' | 'm' | 'l';
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "ui"?: 'primary' | 'secondary' | 'tertiary' | 'ghost' | 'link';
    }
    interface SkInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "inputButtonDisabled"?: boolean;
        /**
          * @default "Send"
         */
        "inputButtonLabel"?: string;
        /**
          * @default "Ask anything..."
         */
        "inputPlaceholder"?: string;
        "onMessageSubmit"?: (event: SkInputCustomEvent<string>) => void;
    }
    interface SkLoading {
        /**
          * @default false
         */
        "active"?: boolean;
        /**
          * @default "Loading"
         */
        "label"?: string;
    }
    interface SkMessage {
        "avatarLabel"?: string;
        /**
          * @default ""
         */
        "content"?: string;
        /**
          * @default "assistant"
         */
        "messageRole"?: MessageRole;
        "timestamp"?: string;
    }
    interface SkSideDrawer {
        "header"?: string;
        "open"?: boolean;
    }
    interface SkSimpleStage {
        /**
          * @default 'Learn more'
         */
        "ctaLabel"?: string;
        /**
          * @default 'Simple stage description for a teaser section.'
         */
        "description"?: string;
        /**
          * @default 'Simple Stage Title'
         */
        "heading"?: string;
        /**
          * @default '78vh'
         */
        "maxHeight"?: string;
        /**
          * @default 'Stage teaser media'
         */
        "mediaAlt"?: string;
        "mediaSrc"?: string;
        /**
          * @default 'image'
         */
        "mediaType"?: 'image' | 'video';
        /**
          * @default '55vh'
         */
        "minHeight"?: string;
        "poster"?: string;
    }
    interface SkTypingIndicator {
    }

    interface SkAiChatAttributes {
        "header": string;
        "subheader": string;
        "inputPlaceholder": string;
        "inputButtonLabel": string;
        "suggestionsLabel": string;
        "loading": boolean;
        "streamingAssistantContent": string;
        "mockLoading": boolean;
        "mockLoadingDelay": number;
        "mockStreaming": boolean;
        "full": boolean;
        "auto": boolean;
        "loadingLabel": string;
    }
    interface SkButtonAttributes {
        "size": 's' | 'm' | 'l';
        "label": string;
        "type": 'button' | 'submit' | 'reset';
        "ui": 'primary' | 'secondary' | 'tertiary' | 'ghost' | 'link';
        "disabled": boolean;
    }
    interface SkInputAttributes {
        "inputPlaceholder": string;
        "inputButtonLabel": string;
        "inputButtonDisabled": boolean;
        "disabled": boolean;
    }
    interface SkLoadingAttributes {
        "active": boolean;
        "label": string;
    }
    interface SkMessageAttributes {
        "messageRole": MessageRole;
        "content": string;
        "timestamp": string;
        "avatarLabel": string;
    }
    interface SkSideDrawerAttributes {
        "header": string;
        "open": boolean;
    }
    interface SkSimpleStageAttributes {
        "heading": string;
        "description": string;
        "ctaLabel": string;
        "mediaType": 'image' | 'video';
        "mediaSrc": string;
        "poster": string;
        "mediaAlt": string;
        "minHeight": string;
        "maxHeight": string;
    }

    interface IntrinsicElements {
        "sk-ai-chat": Omit<SkAiChat, keyof SkAiChatAttributes> & { [K in keyof SkAiChat & keyof SkAiChatAttributes]?: SkAiChat[K] } & { [K in keyof SkAiChat & keyof SkAiChatAttributes as `attr:${K}`]?: SkAiChatAttributes[K] } & { [K in keyof SkAiChat & keyof SkAiChatAttributes as `prop:${K}`]?: SkAiChat[K] };
        "sk-button": Omit<SkButton, keyof SkButtonAttributes> & { [K in keyof SkButton & keyof SkButtonAttributes]?: SkButton[K] } & { [K in keyof SkButton & keyof SkButtonAttributes as `attr:${K}`]?: SkButtonAttributes[K] } & { [K in keyof SkButton & keyof SkButtonAttributes as `prop:${K}`]?: SkButton[K] };
        "sk-input": Omit<SkInput, keyof SkInputAttributes> & { [K in keyof SkInput & keyof SkInputAttributes]?: SkInput[K] } & { [K in keyof SkInput & keyof SkInputAttributes as `attr:${K}`]?: SkInputAttributes[K] } & { [K in keyof SkInput & keyof SkInputAttributes as `prop:${K}`]?: SkInput[K] };
        "sk-loading": Omit<SkLoading, keyof SkLoadingAttributes> & { [K in keyof SkLoading & keyof SkLoadingAttributes]?: SkLoading[K] } & { [K in keyof SkLoading & keyof SkLoadingAttributes as `attr:${K}`]?: SkLoadingAttributes[K] } & { [K in keyof SkLoading & keyof SkLoadingAttributes as `prop:${K}`]?: SkLoading[K] };
        "sk-message": Omit<SkMessage, keyof SkMessageAttributes> & { [K in keyof SkMessage & keyof SkMessageAttributes]?: SkMessage[K] } & { [K in keyof SkMessage & keyof SkMessageAttributes as `attr:${K}`]?: SkMessageAttributes[K] } & { [K in keyof SkMessage & keyof SkMessageAttributes as `prop:${K}`]?: SkMessage[K] };
        "sk-side-drawer": Omit<SkSideDrawer, keyof SkSideDrawerAttributes> & { [K in keyof SkSideDrawer & keyof SkSideDrawerAttributes]?: SkSideDrawer[K] } & { [K in keyof SkSideDrawer & keyof SkSideDrawerAttributes as `attr:${K}`]?: SkSideDrawerAttributes[K] } & { [K in keyof SkSideDrawer & keyof SkSideDrawerAttributes as `prop:${K}`]?: SkSideDrawer[K] };
        "sk-simple-stage": Omit<SkSimpleStage, keyof SkSimpleStageAttributes> & { [K in keyof SkSimpleStage & keyof SkSimpleStageAttributes]?: SkSimpleStage[K] } & { [K in keyof SkSimpleStage & keyof SkSimpleStageAttributes as `attr:${K}`]?: SkSimpleStageAttributes[K] } & { [K in keyof SkSimpleStage & keyof SkSimpleStageAttributes as `prop:${K}`]?: SkSimpleStage[K] };
        "sk-typing-indicator": SkTypingIndicator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sk-ai-chat": LocalJSX.IntrinsicElements["sk-ai-chat"] & JSXBase.HTMLAttributes<HTMLSkAiChatElement>;
            "sk-button": LocalJSX.IntrinsicElements["sk-button"] & JSXBase.HTMLAttributes<HTMLSkButtonElement>;
            "sk-input": LocalJSX.IntrinsicElements["sk-input"] & JSXBase.HTMLAttributes<HTMLSkInputElement>;
            "sk-loading": LocalJSX.IntrinsicElements["sk-loading"] & JSXBase.HTMLAttributes<HTMLSkLoadingElement>;
            "sk-message": LocalJSX.IntrinsicElements["sk-message"] & JSXBase.HTMLAttributes<HTMLSkMessageElement>;
            "sk-side-drawer": LocalJSX.IntrinsicElements["sk-side-drawer"] & JSXBase.HTMLAttributes<HTMLSkSideDrawerElement>;
            "sk-simple-stage": LocalJSX.IntrinsicElements["sk-simple-stage"] & JSXBase.HTMLAttributes<HTMLSkSimpleStageElement>;
            "sk-typing-indicator": LocalJSX.IntrinsicElements["sk-typing-indicator"] & JSXBase.HTMLAttributes<HTMLSkTypingIndicatorElement>;
        }
    }
}
